name: switchfin
summary: switchfin
description: |
  third-party PC player for Jellyfin
version: "0.1.0"
grade: stable
icon: resources/icon/icon.png
base: core20
confinement: strict

apps:
  switchfin:
    command: usr/bin/Switchfin
    plugs:
    - desktop
    - wayland
    - x11
    - opengl
    - network

layout:
  /usr/lib/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/lib/resources:
    bind: $SNAP/usr/lib/resources
  
parts:
  libmpv:
    source: https://github.com/mpv-player/mpv/archive/v0.35.1.tar.gz
    source-type: tar
    plugin: meson
    meson-parameters:
    - -Dprefix=/usr
    - -Dbuildtype=release
    - -Dbuild-date=false
    - -Ddefault_library=shared
    - -Dcplayer=false
    - -Dlibmpv=true
    - -Dtests=false
    - -Dplain-gl=enabled
    build-packages:
    - libavfilter-dev
    - libass-dev
    stage-packages:
    - libavfilter7
    prime:
    - -etc
    - -usr/bin/fc-*
    - -usr/bin/update-mime-database
    - -usr/share
    - -usr/include

  switchfin:
    plugin: cmake
    source: '.'
    source-type: local
    cmake-parameters:
    - -DPLATFORM_DESKTOP=ON
    - -DCMAKE_BUILD_TYPE=Release
    - -DCMAKE_INSTALL=ON
    - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
    - g++
    - xorg-dev
    - libdbus-1-dev
    - libcurl4-openssl-dev
    stage-packages:
    - libgl1-mesa-glx
    - libgl1-mesa-dri
    - libcurl4
    after:
    - libmpv
    prime:
    - -etc
    - -usr/bin/fc-*
    - -usr/share
