name: Build

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  build-switch:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Build dependencies
      if: ${{ github.ref_name == '0.1.0' }}
      run: |
        apt-get update
        apt-get upgrade -y patch fakeroot file zstd
        
        adduser --gecos '' --disabled-password builder
        echo 'builder ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/builder
        chown -R builder:builder $(pwd)/scripts/switch

        dkp-pacman --noconfirm -U scripts/switch/dkp-toolchain-vars-1.0.3-2-any.pkg.tar.zst
        su - builder -c "make -C $(pwd)/scripts/switch -j$(nproc)"
    - name: Update dependencies
      if: ${{ github.ref_name != '0.1.0' }}
      run: |
        dkp-pacman --noconfirm -U https://github.com/${{ github.repository }}/releases/download/0.1.0/switch-ffmpeg-4.4.4-1-any.pkg.tar.zst
        dkp-pacman --noconfirm -U https://github.com/${{ github.repository }}/releases/download/0.1.0/switch-libmpv-0.35.1-1-any.pkg.tar.zst
    - name: Build nro
      run: |
        cmake -B switch -DPLATFORM_SWITCH=ON
        make -C switch Switchfin.nro -j$(nproc)
        cmake -E tar c Switchfin-NintendoSwitch.zip switch/Switchfin.nro
    - name: Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: |
          Switchfin-NintendoSwitch.zip
          scripts/switch/*/*.pkg.tar.zst

  build-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Install deps
      run: |
        brew install create-dmg dylibbundler webp
        brew tap xfangfang/wiliwili
        brew install -v mpv-wiliwili
    - name: Build
      run: |
        BRLS_GLFW="library/borealis/library/lib/extern/glfw/"
        cmake -P ${BRLS_GLFW}/CMake/GenerateMappings.cmake ${BRLS_GLFW}/src/mappings.h.in ${BRLS_GLFW}/src/mappings.h

        cmake -B build -DPLATFORM_DESKTOP=ON -DCMAKE_BUILD_TYPE=Release
        make -C build Switchfin.app -j$(sysctl -n hw.ncpu)

        mkdir -p dist
        mv build/Switchfin.app dist/
        cp README.md dist
        create-dmg --window-pos 200 120 --window-size 800 400 \
          --icon-size 100 --icon "Switchfin.app" 200 190 \
          --icon "README.md" 400 100 --hide-extension "Switchfin.app" \
          --app-drop-link 600 185 --volicon ./scripts/dmg.icns \
          --volname "Switchfin" Switchfin-macOS.dmg "dist/"
    - name: Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: Switchfin-macOS.dmg

  build-windows:
    runs-on: windows-2022
    steps:
    - name: Setup Windows 10 SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
      with:
        sdk-version: 19041
    - name: Install xmake
      shell: powershell
      run: |
        Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Cache xmake packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-build
        path: |
          ${{ runner.temp }}/.xmake/packages
    - name: Build
      shell: powershell
      run: |
        $env:path+=";$env:USERPROFILE\xmake"
        $env:XMAKE_GLOBALDIR="${{ runner.temp }}"
        xmake config -c -y
        xmake build -y
        cd build\windows\x64\release
        7z a "$env:GITHUB_WORKSPACE\Switchfin-Win64.zip" *
    - name: Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: Switchfin-Win64.zip
      
        
